# Generated by Django 6.0.3 on 2026-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('app_label', models.CharField(blank=True, max_length=100)),
                ('permission_codename', models.CharField(blank=True, max_length=100)),
                ('menu_group', models.CharField(default='Geral', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['menu_group', 'order', 'name'],
            },
        ),
    ]
