# Generated by Django 6.0.3 on 2026-03-31 18:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterfacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_refresh_enabled', models.BooleanField(default=True)),
                ('auto_refresh_interval', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de interface',
                'verbose_name_plural': 'Preferências de interface',
            },
        ),
    ]
