# Generated by Django 6.0.3 on 2026-04-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apiaccessprofile_apitoken_apiresourcepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresourcepermission',
            name='resource',
            field=models.CharField(choices=[('panel.users', 'Usuários'), ('panel.groups', 'Grupos'), ('core.api_access', 'Acesso à API'), ('core.audit_logs', 'Logs de auditoria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Falha de login'), ('api_access_denied', 'Acesso negado à API'), ('rate_limited', 'Rate limit')], max_length=20),
        ),
    ]
