# Generated by Django 6.0.3 on 2026-04-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_apiresourcepermission_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresourcepermission',
            name='resource',
            field=models.CharField(choices=[('panel.users', 'Usuários'), ('panel.groups', 'Grupos'), ('panel.modules', 'Módulos'), ('core.api_access', 'Acesso à API'), ('core.audit_logs', 'Logs de auditoria')], max_length=50),
        ),
    ]
