# Generated by Django 6.0.3 on 2026-04-04 15:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_auditlog_core_audit_ct_obj_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterfacepreference',
            name='session_idle_timeout_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Define o tempo maximo de inatividade da sessao, em minutos. Deixe em branco para nao aplicar regra propria neste usuario.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.CreateModel(
            name='GroupInterfacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_idle_timeout_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Define o tempo maximo de inatividade da sessao para membros do grupo, em minutos. Deixe em branco para nao aplicar regra neste grupo.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to='auth.group')),
            ],
            options={
                'verbose_name': 'Preferência de grupo',
                'verbose_name_plural': 'Preferências de grupos',
            },
        ),
    ]
