"""Rotas do painel administrativo interno."""

from django.urls import path

from .views import (
                    admin_account_activate,
                    admin_account_create,
                    admin_account_deactivate,
                    admin_account_delete,
                    admin_account_update,
                    admin_accounts_list,
                    audit_log_detail,
                    audit_logs_export_csv,
                    audit_logs_export_json,
                    audit_logs_list,
                    group_create,
                    group_delete,
                    group_update,
                    groups_list,
                    login_security_cleanup_expired_attempts,
                    login_security_list,
                    login_security_reset_attempt,
                    module_activate,
                    module_create,
                    module_deactivate,
                    module_delete,
                    module_update,
                    modules_list,
                    user_activate,
                    user_create,
                    user_deactivate,
                    user_delete,
                    user_update,
                    users_list,
)

urlpatterns = [
    path(
        "administracao/usuarios/",
        admin_accounts_list,
        name="panel_admin_accounts_list",
    ),
    path(
        "administracao/usuarios/novo/",
        admin_account_create,
        name="panel_admin_account_create",
    ),
    path(
        "administracao/usuarios/<int:pk>/ativar/",
        admin_account_activate,
        name="panel_admin_account_activate",
    ),
    path(
        "administracao/usuarios/<int:pk>/inativar/",
        admin_account_deactivate,
        name="panel_admin_account_deactivate",
    ),
    path(
        "administracao/usuarios/<int:pk>/excluir/",
        admin_account_delete,
        name="panel_admin_account_delete",
    ),
    path(
        "administracao/usuarios/<int:pk>/editar/",
        admin_account_update,
        name="panel_admin_account_update",
    ),
    path("auditoria/", audit_logs_list, name="panel_audit_logs_list"),
    path(
        "auditoria/exportar/csv/",
        audit_logs_export_csv,
        name="panel_audit_logs_export_csv",
    ),
    path(
        "auditoria/exportar/json/",
        audit_logs_export_json,
        name="panel_audit_logs_export_json",
    ),
    path("auditoria/<int:pk>/", audit_log_detail, name="panel_audit_log_detail"),
    path("seguranca/login/", login_security_list, name="panel_login_security_list"),
    path(
        "seguranca/login/limpar-expiradas/",
        login_security_cleanup_expired_attempts,
        name="panel_login_security_cleanup_expired_attempts",
    ),
    path(
        "seguranca/login/tentativas/<int:pk>/resetar/",
        login_security_reset_attempt,
        name="panel_login_security_reset_attempt",
    ),
    path("modulos/", modules_list, name="panel_modules_list"),
    path("modulos/novo/", module_create, name="panel_module_create"),
    path("modulos/<int:pk>/ativar/", module_activate, name="panel_module_activate"),
    path("modulos/<int:pk>/inativar/", module_deactivate, name="panel_module_deactivate"),
    path("modulos/<int:pk>/excluir/", module_delete, name="panel_module_delete"),
    path("modulos/<int:pk>/editar/", module_update, name="panel_module_update"),
    path("usuarios/", users_list, name="panel_users_list"),
    path("usuarios/novo/", user_create, name="panel_user_create"),
    path("usuarios/<int:pk>/ativar/", user_activate, name="panel_user_activate"),
    path("usuarios/<int:pk>/inativar/", user_deactivate, name="panel_user_deactivate"),
    path("usuarios/<int:pk>/excluir/", user_delete, name="panel_user_delete"),
    path("usuarios/<int:pk>/editar/", user_update, name="panel_user_update"),
    path("grupos/", groups_list, name="panel_groups_list"),
    path("grupos/novo/", group_create, name="panel_group_create"),
    path("grupos/<int:pk>/excluir/", group_delete, name="panel_group_delete"),
    path("grupos/<int:pk>/editar/", group_update, name="panel_group_update"),
]
